# Generated by Django 4.2.4 on 2023-12-04 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('feedback_score', models.IntegerField(default=5)),
                ('feedback_content', models.TextField(default='')),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('feedback_manuscript', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.manuscript')),
                ('feedback_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
