# Generated by Django 4.2.7 on 2023-12-03 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('manuscript_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('manuscript_title', models.CharField(default='', max_length=200)),
                ('manuscript_abstract', models.TextField(default='')),
                ('manuscript_api', models.TextField(default='')),
                ('novelty_score', models.IntegerField(default=1)),
                ('similarity_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('manuscript_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
